// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAejbHFBW2ou1VSQrr70uBO0FVx1dcd1iw',
    appId: '1:820448289332:web:57103f0a5893c3cb2aa061',
    messagingSenderId: '820448289332',
    projectId: 'infralert-9193c',
    authDomain: 'infralert-9193c.firebaseapp.com',
    storageBucket: 'infralert-9193c.appspot.com',
    measurementId: 'G-BZS19B91N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs5gPFMYLPx0K9Z-qVCjG8J-biyzsd4N0',
    appId: '1:820448289332:android:dee13da5108dde402aa061',
    messagingSenderId: '820448289332',
    projectId: 'infralert-9193c',
    storageBucket: 'infralert-9193c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMIV0CjtNKewPrYZ0aD_A90b_QlQQh-K4',
    appId: '1:820448289332:ios:6e826a3c79c72c5c2aa061',
    messagingSenderId: '820448289332',
    projectId: 'infralert-9193c',
    storageBucket: 'infralert-9193c.appspot.com',
    iosBundleId: 'com.example.infralert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMIV0CjtNKewPrYZ0aD_A90b_QlQQh-K4',
    appId: '1:820448289332:ios:6e826a3c79c72c5c2aa061',
    messagingSenderId: '820448289332',
    projectId: 'infralert-9193c',
    storageBucket: 'infralert-9193c.appspot.com',
    iosBundleId: 'com.example.infralert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAejbHFBW2ou1VSQrr70uBO0FVx1dcd1iw',
    appId: '1:820448289332:web:f8878e0fb6b248792aa061',
    messagingSenderId: '820448289332',
    projectId: 'infralert-9193c',
    authDomain: 'infralert-9193c.firebaseapp.com',
    storageBucket: 'infralert-9193c.appspot.com',
    measurementId: 'G-ERCF9MX7XS',
  );

}